vesion: '3.8'

services:
  app:
    build: .
    image: volteros/to-do-listapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_DATABASE: permalist
      DB_PASSWORD: 135346
      DB_PORT: 5432

  db:
    images: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: permalist
      POSTGRES_PASSWORD: 135346
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes: postgres_data