services:
  app:
    build: .
    image: volteros/to-do-listapp
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_DATABASE: permalist
      DB_PASSWORD: 135346
      DB_PORT: 5432
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: permalist
      POSTGRES_PASSWORD: 135346
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  postgres_data: